### ISSUE TITLE
Rectangle surrounding figures

### ISSUE THREAD

**Issue by noamross** [hadley/svglite#41]
In rendering a ggplot with

    plot.background = element_rect(fill = "transparent", colour = NA))

svglite still includes

    <rect width='100%' height='100%'/>

which renders as an outline around the entire figure, as the `<style>` tags set the `rect` stroke to black

**Comment by hadley** [comment]
@yixuan any thoughts on how to fix this? That rectangle should be getting `style="stroke: transparent;"` right?

**Comment by yixuan** [comment]
Ah, it seems that the `<rect>` element in `svg_new_page()` was not well set. I'll give a patch later today.

**Comment by yixuan** [comment]
It turns out that there should not be a `<rect>` in the `svg_new_page()` function, so after removing it the rendering will be correct.

**Comment by yixuan** [comment]
@noamross 
I think this has been fixed by https://github.com/hadley/svglite/pull/42, but note that `svglite()` has a default parameter `bg = "white"`, so even if `plot.background` is set to `fill = "transparent"`, you will still see a white background, unless you use `svglite(bg = "transparent")`.
