### ISSUE TITLE
ggplot2: One line of panel.background always gets dropped

### ISSUE THREAD

**Issue by expersso** [hadley/svglite#47]
```
library(ggplot2)
library(svglite)

svglite("testplot.svg")
qplot(mtcars$cyl) + theme_bw()
dev.off()
```

![testplot](https://cloud.githubusercontent.com/assets/7280464/11742028/18c79100-9ffd-11e5-8454-1c00b4b146cc.png)

**Comment by expersso** [comment]
An even more minimal example:

```
library(ggplot2)
library(svglite)

svglite("testplot.svg")
ggplot(NULL) + theme(text = element_blank(), 
                     axis.ticks = element_blank(),
                     panel.background = element_rect(color = "black"),
                     panel.grid = element_blank())

dev.off()
```

```
<?xml version='1.0' encoding='UTF-8' ?>
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 720.00 576.00'>
<defs>
  <style type='text/css'><![CDATA[
    line, polyline, path, rect, circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
  ]]></style>
</defs>
<rect width='100%' height='100%' style='stroke: none; fill: #FFFFFF;'/>
<polyline points='0.00,576.00 0.00,0.00 720.00,0.00 720.00,576.00 ' style='stroke-width: 1.07; stroke: #FFFFFF; fill: #FFFFFF;' />
<polyline points='5.48,570.52 5.48,5.48 714.52,5.48 714.52,570.52 ' style='stroke-width: 1.07; fill: #EBEBEB;' />
</svg>
```
 The last polyline only draws three of the four sides.

**Comment by yixuan** [comment]
I think I figured out the cause of the problem.

The reason why one line was dropped off is that the current `svglite` does not support clipping, so R will calculate the boundary of the plot and remove elements that are outside of it. Due to some rounding errors one or more border lines get a chance to be removed.

If we do not provide our own `clip()` device function, there seems to be no way to avoid it.

**Comment by hadley** [comment]
@yixuan clipping shouldn't be too hard to implement, right? We can just continue to draw everything, but put it in an element that clips? (Hmmmm, after reading the svg docs a bit this might be hard because we need to declare a `<clipPath>` at the top of the doc)

**Comment by yixuan** [comment]
It seems possible to implement a `clip()` device function in `svglite`: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Clipping_and_masking, with the price that each element will gain another attribute `clip-path`.

**Comment by yixuan** [comment]
I believe we can define multiple `<clipPath>` in the body of SVG and assign each one an ID. Then the following elements just need to refer to the proper clip path.

**Comment by hadley** [comment]
Oh I see you can define it just before you use it:

```xml
<g clip-rule="nonzero">
  <clipPath id="MyClip">
    <path d="..." clip-rule="evenodd" />
  </clipPath>
  <rect clip-path="url(#MyClip)" ... />
</g>
```

**Comment by yixuan** [comment]
Yep. I could try to make a PR today to implement this.

**Comment by hadley** [comment]
That would be awesome - I want to aim for a release around Feb 12
