### ISSUE TITLE
long numbers on y-axis overlap with ticks

### ISSUE THREAD

**Issue by Lompik** [hadley/svglite#48]
reproducible example : 

    library(svglite)
    library(ggplot2)
    a = data.frame(x=runif(1000,0,10), y= rnorm(1000,10,5)*1000)
    svglite("test1.svg", width = 8, height = 10,bg="white")
    ggplot(a,aes(x=x,y=y))+geom_line()
    dev.off()

output : 

![2015-12-11-12 55 05_126x411 3328 347](https://cloud.githubusercontent.com/assets/3791334/11752676/82908340-a006-11e5-8b74-f32d01e21927.png)

**Comment by hadley** [comment]
Probably an instance of #45
