### ISSUE TITLE
htmlSVG as graphics device?

### ISSUE THREAD

**Issue by noamross** [hadley/svglite#51]
I often have a bit of a headache moving from R figures shown in the interactive graphics device, which I create during the exploratory phase of analysis, to those in a knitted report, because sizing is different.  `htmlSVG()` is a great help for this.  Is it possible to create a device, such as `dev.htmlSVG()`, that would create a plot with a fixed size in the RStudio viewer pane as the normal print method?  This would make one's initial plots translate to finished product more easily.

**Comment by timelyportfolio** [comment]
I could easily be misunderstanding the question, but I wanted to make sure you knew that you can pass `height` and `width` to `htmlSVG`.

```
htmlSVG({plot(1:3)},height=4,width=4)
```

**Comment by noamross** [comment]
Right.  What I'd like to do, though, is set `dev.HTMLsvg(height=4, width=4)` once, and from then on any plotting commands in the session would show up in the HTML viewer, rather than the figures pane.  Behavior would revert with `dev.off()` or some other new device being invoked.

**Comment by hadley** [comment]
This seems too specialised for svglite, in my opinion.

**Comment by noamross** [comment]
Implemented experimentally at https://github.com/noamross/svglite/tree/svglitedev @timelyportfolio
