### ISSUE TITLE
Fix 3.1.1 problem

### ISSUE THREAD

**Issue by hadley** [hadley/svglite#52]
https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/svglite-00check.html

**Comment by davidgohel** [comment]
I am not sure, but `plot.raster` was not yet implemented in the oldrel release.

**Comment by davidgohel** [comment]
ok... just ignore my comment, it's in the title

**Comment by hadley** [comment]
Fixed in ac66efa078884f8e94ec5bc50c4cc423dce187ad
