### ISSUE TITLE
Pango-warning/rendering of symbols

### ISSUE THREAD

**Issue by masalmon** [hadley/svglite#54]
I'm using R in RStudio on a Windows machine. I've used svg() and svglite() to produce a svg.
```r
# create an svg image
library(svglite)
library(ggplot2)
library(rsvg)

# svg image 1 with svg()
svg("plot.svg", width = 10, height = 7)
qplot(mpg, wt, data = mtcars, colour = factor(cyl),
      xlab=expression(paste("PM2.5 exposure (log ", mu, "g/",m^3,")")))
dev.off()
bitmap <- rsvg("plot.svg")
png::writePNG(bitmap, "bitmap.png")

# svg image 2 with svglite()
svglite("plot2.svg", width = 10, height = 7)
qplot(mpg, wt, data = mtcars, colour = factor(cyl),
      xlab=expression(paste("PM2.5 exposure (log ", mu, "g/",m^3,")")))
dev.off()
bitmap <- rsvg("plot2.svg")
png::writePNG(bitmap, "bitmap2.png")
```

With svglite I get the warning "(rsession.exe:5240): Pango-WARNING **: couldn't load font "symbol Not-Rotated 11", falling back to "Sans Not-Rotated 11", expect ugly output.". With svg I don't. The output from svglite doesn't get symbols right in the x-label -- well I'd been warned to expect an ugly output. 

![bitmap](https://cloud.githubusercontent.com/assets/8360597/12547836/de419624-c352-11e5-98d2-883661d05cf3.png)
![bitmap2](https://cloud.githubusercontent.com/assets/8360597/12547835/de3d9204-c352-11e5-89fa-2b9c770d7d9f.png)

I wonder whether this is a svglite issue or something else on my PC? I googled Pango-warnings but I didn't get wiser.

**Comment by hadley** [comment]
Could you please confirm this simpler reprex gives you the same warning:

```R
htmlSVG({
  plot.new()
  text(0.5, 0.5, expression(a ^ b))
})
```

**Comment by masalmon** [comment]
No I only get "package ‘gdtools’ was built under R version 3.2.3 ". (my R version is "R version 3.2.2 (2015-08-14) -- "Fire Safety"" -> maybe it is the issue, in which case I'm sorry. I need to ask IT services to update my R version and try everything again!)

**Comment by masalmon** [comment]
Update: I installed the newest version of svglite from Github and am now using it in the latest R version. 

* I receive no warning for the reprex with htmlSVG.

* When using my own code from above I receive the old warning again "Pango-WARNING **: couldn't load font "symbol Not-Rotated 11", falling back to "Sans Not-Rotated 11", expect ugly output." But the output is no longer ugly!

![bitmap](https://cloud.githubusercontent.com/assets/8360597/12914838/fc478ffe-cf26-11e5-8ebf-6e3b3acd1ad9.png)
![bitmap2](https://cloud.githubusercontent.com/assets/8360597/12914839/fc4a85f6-cf26-11e5-9d06-98052ad2a5f4.png)

**Comment by hadley** [comment]
Seems like it must be something idiosyncratic with your system.

**Comment by masalmon** [comment]
ok thanks!
