### ISSUE TITLE
Japanese text placed wrong

### ISSUE THREAD

**Issue by okumuralab** [hadley/svglite#59]
```
svglite("dnorm.svg", width=7, height=4)
curve(dnorm(x), xlim=c(-3,3), main="正規分布")
dev.off()
```

places Japanese string "正規分布" in wrong position.  If the width cannot be determined, it'd be better to center the text like &lt;text ... text-anchor="middle"&gt;正規分布&lt;/text&gt;.

A related issue: cex=0.5 doesn't work.

**Comment by hadley** [comment]
The underlying problem is 

```R
gdtools::str_metrics("正規分布")
#>  width  ascent descent 
#>     0       0       0 
```

I think because R has some fall back that it uses when the symbol is not available in the current font

**Comment by hadley** [comment]
@davidgohel any idea why this fails, but it works ok in R?  The base R code is at https://github.com/wch/r-source/blob/master/src/library/grDevices/src/cairo/cairoFns.c#L524.
