### ISSUE TITLE
use unique ids

### ISSUE THREAD

**Issue by timelyportfolio** [hadley/svglite#67]
When using mutliple svg from `svglite` in the browser, the `id` for `clippath` and other elements will very likely conflict.  Would it be possible to use `uuid` to prevent this conflict?

**Comment by hadley** [comment]
Please provide a reproducible example of the problem.

**Comment by timelyportfolio** [comment]
Sure, if you open this in Chrome (seems to be the most reliable in showing the bug),  you will see the `clipPath` from the first plot is applied to the second, since the `DOM` requires unique selector `id`.  There is a `#cp1` and `#cp2` for both plots, and the `cp1` and `cp2` are applied to the second plot.

```r
library(svglite)
library(htmltools)

browsable(
  tagList(
    htmlSVG({plot(1:10,pch=10)},height=4,width=7),
    htmlSVG({contour(volcano)},height=20,width=20)
  )
)
```

![image](https://cloud.githubusercontent.com/assets/837910/17676880/024f09dc-62f6-11e6-9c96-2f2476cb9ced.png)


![image](https://cloud.githubusercontent.com/assets/837910/17677106/e93df470-62f6-11e6-8963-4d238a9488fd.png)


Deleting the `cp2` from the first corrects the problem.

![svglite_nonuniqueid](https://cloud.githubusercontent.com/assets/837910/17677259/a15852ee-62f7-11e6-891f-246671be2e81.gif)

**Comment by lionel-** [comment]
@timelyportfolio I don't see uuid in the SVG spec. What do you mean?

@hadley generating random ids seems like it would create difficulties regarding reproducibility. I think it would be better to add an argument `id_prefix = ""` to all device functions, what do you think?

**Comment by hadley** [comment]
@lionel- alternatively maybe we could use a simple hashing algorithm to ensure that the id is unique? There's only four values, so it shouldn't be too hard

**Comment by timelyportfolio** [comment]
`uuid` is not in the SVG spec.  Here is the Wiki [definition](https://en.wikipedia.org/wiki/Universally_unique_identifier).  For reference, here is how it is handled in `htmlwidgets` https://github.com/ramnathv/htmlwidgets/pull/213.

**Comment by lionel-** [comment]
@timelyportfolio thanks!

@hadley would using `boost::hash()` on a `std::pair()` of `std::pair()` be a reasonable approach?

**Comment by hadley** [comment]
Sure, although it might be just as easy to code up something by hand, e.g. paste together the hex representation of each value (maybe coerce to float to make shorter?)

**Comment by timelyportfolio** [comment]
Unfortunately, this solution does not rectify the situation. Using the same reproducible example as before, I get the same clippaths for each svg.  Am I missing something?

```
![image](https://cloud.githubusercontent.com/assets/837910/19648764/d98bdb7e-99c8-11e6-8286-1575ce51ba4a.png)
```

**Comment by lionel-** [comment]
yes there was a bug but already fixed, soon to be on master ;)

**Comment by timelyportfolio** [comment]
Great thanks!
