### ISSUE TITLE
svglite output different than grDevices::svg, png

### ISSUE THREAD

**Issue by dekellum** [hadley/svglite#68]
Here is minimal reproducible script extracted from hadley/ggplot2#1686

Using ggplot2 2.1.0:

~~~ R
library(ggplot2)

p = ggplot(data.frame(x=1:10, y=1:10)) +
  geom_point(aes(x=x, y=y)) +
  geom_text( aes( x=x, y=y, label=y ), nudge_x=0.5 ) +
  theme( panel.grid.major.x = element_blank(), panel.grid.minor = element_blank() ) +
  theme( panel.grid.major.y = element_line(color = "#AAAAAA", linetype="dashed", size=0.33) )

ggsave( "svg_test.png", p, width=5.1, height=5.1 )
ggsave( "svg_test_svglite.svg", p, width=5.1, height=5.1 )
ggsave( "svg_test_gr.svg", p, width=5.1, height=5.1, device = grDevices::svg )
~~~

When comparing svg_test_svglite.svg to both svg_test_gr.svg and svg_test.png:

1. svglite output doesn't honor panel.grid.major.y linetype="dashed"
2. svglite output has viewBox="0 0 367.20 367.20", where as "grDevices::svg" output has width="367pt" height="367pt" and viewBox= "0 0 367 367"

I'm no expert on SVG, but (2) can effect the size of the SVG embedded in a web page if it is not otherwise set.  Also if the web page does specify a fixed size, the svglite output might appear to have larger fonts than intended (since the entire rendering will be upscaled). Based on this the "grDevices::svg" output appears more comparable to the png and thus more correct.

**Comment by hadley** [comment]
I'm pretty sure the current sizing specification is correct, based on discussion with Paul Murrell.

Minimal reprex for dashing problem:

```R
library(ggplot2)
p <- ggplot(data.frame(x = 1, y = 1), aes(x, y)) +
  scale_x_continuous(NULL, breaks = NULL) + 
  scale_y_continuous(NULL, breaks = 1, labels = NULL) +
  geom_point() +
  theme_minimal() + 
  theme( 
    panel.grid.major.y = element_line(colour = "black", linetype = "dashed")
  )

p
```

**Comment by hadley** [comment]
Even more minimal reprex:

```R
htmlSVG({
  plot.new()
  abline(h = 0.25, lty = "dashed", lwd = 0.5)
  abline(h = 0.5, lty = "dashed", lwd = 1)
  abline(h = 0.75, lty = "dashed", lwd = 5)
})
```
