### ISSUE TITLE
Output differs across platforms

### ISSUE THREAD

**Issue by lionel-** [hadley/svglite#69]
The following:

```r
library("ggplot2")

p <- ggplot(mtcars, aes(disp, cyl)) + geom_point()

svg <- svglite::svgstring()
tryCatch(
  print(p),
  finally = grDevices::dev.off()
)
svg()
```

produces plots with different spacing on Linux and OSX.

[issue-svg.zip](https://github.com/hadley/svglite/files/415981/issue-svg.zip)

**Comment by hadley** [comment]
Can you try running this on both platforms:

```R
gdtools::str_metrics("disp")
#>     width    ascent   descent 
#> 22.013672  8.636719  2.501953 
```

**Comment by lionel-** [comment]
In the Debian:testing docker I have:

```r
gdtools::str_metrics("disp")
##    width   ascent  descent 
## 24.82031  9.12500  2.50000 
```

And on OSX:

```r
gdtools::str_metrics("disp")
##   width  ascent descent 
##   22.01    8.64    2.50 
```

**Comment by lionel-** [comment]
Oops, with the full decimal places, the OSX metrics are exactly the same as yours.

**Comment by hadley** [comment]
Can you file on https://github.com/davidgohel/gdtools and see if David has any ideas?

**Comment by davidgohel** [comment]
Almost ready...

You can test it with the following R commands

```
devtools::install_github('davidgohel/fontquiver')
devtools::install_github('lionel-/fontHeavy')
devtools::install_github('davidgohel/gdtools')
devtools::install_github('davidgohel/svglite')
```

Using bitstream vera as default font is not ideal as this font does not offer *serif italic* neither *serif bolditalic*. I would prefer a mix of fonts:

* *sans* & *mono* could be *bitstream vera* sans and mono
* *serif* could be *dejavu* (or another one) but with regular/bold/italic/bolditalic
