### ISSUE TITLE
Segfault in svglite 1.2.0

### ISSUE THREAD

**Issue by jeroenooms** [hadley/svglite#80]
An example in the `rsvg` package is segfaulting after the `svglite` update (or perhaps one of it's dependencies). The problem is in svglite; I can reproduce the problem without rsvg as well (on the latest Fedora stable). 

The crash appears somewhat randomly which suggests a memory corruption caused earlier on. A reproducible example without rsvg:

```r
options(example.ask=FALSE)
tmp <- tempfile()

# Create svg with basic SG
svg(tmp, width = 10, height = 7)
ggplot2::qplot(mpg, wt, data = mtcars, colour = factor(cyl))
dev.off()

# start svglite devices causes crash
svglite::svglite(tmp, width = 10, height = 7)
## R: fccache.c:545: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.
## Aborted
```

This problem does not appear on mac and windows I think.

**Comment by lionel-** [comment]
judging from the error message, that would be gdtools. I'll look into it.

> This problem does not appear on mac and windows I think.

I ran `revdep_check()` on a mac :/

**Comment by jeroenooms** [comment]
On mac you can test using docker for mac:

```sh
docker pull fedora:latest
docker run -i -t fedora:latest /bin/bash
```

And then install R and svglite, etc.

**Comment by lionel-** [comment]
Could you give the result of `gdtools::version_fontconfig()` please.

**Comment by lionel-** [comment]
Seems to affect Shiny as well: https://groups.google.com/forum/#!topic/shiny-discuss/5kuGWnEb_LE

**Comment by timelyportfolio** [comment]
I just checked on Windows 10, and no error.  It did hang for a while but eventually worked.

**Comment by lionel-** [comment]
The hang is fontconfig building a cache of the system fonts and should only happen once.

**Comment by timelyportfolio** [comment]
second try was quick as you suggest.  Thanks!

**Comment by lionel-** [comment]
I think it's because the Cairo svg device initialise fontconfig only once per session:

https://github.com/wch/r-source/blob/7a39bb9cf2d90571209d82f826976d53faf10bf8/src/library/grDevices/src/cairo/cairoFns.c#L678

So we should never finalise fontconfig in gdtools.
