### ISSUE TITLE
svglite doesn't connect polygon start to end

### ISSUE THREAD

**Issue by ilia-kats** [hadley/svglite#82]
Compare:
```
x11()
library(vioplot)
vioplot(1:10)
```
to
```
library(svglite)
svglite()
vioplot(1:10)
dev.off()
```
The bottom border of the violin plot is not drawn with svglite.

**Comment by ilia-kats** [comment]
Sorry that it took me so long to notice, but this fix now leads to the situtation where lines() always joins its endpoints, as in
```
library(svglite)
svglite()
plot(1:10)
lines(c(2, 2, 3, 3), c(2, 3, 3, 2))
dev.off()
```

**Comment by lionel-** [comment]
have you tried with recent master?

**Comment by ilia-kats** [comment]
right, my bad, sorry

**Comment by lionel-** [comment]
no worries
